/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ConstructionRole;

import Business.EcoSystem;
import Business.Utility.Helper;
import Business.Utility.Validation;
import Business.WorkeQueue.ConstructionWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.ElectricityRole.ElectricityProcessWorkRequestJPanel;

/**
 *
 * @author raunak
 */
public class ConstructionProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    ConstructionWorkRequest request;
    EcoSystem buisness;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ConstructionProcessWorkRequestJPanel(JPanel userProcessContainer, ConstructionWorkRequest request,EcoSystem buisness) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.buisness=buisness;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setBackground(new java.awt.Color(51, 51, 51));
        submitJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 110, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 96, 40));

        resultJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultJTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        resultJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                resultJTextFieldKeyTyped(evt);
            }
        });
        add(resultJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 270, 40));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Pictures/1417743630_go-previous-24.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Process Request");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 43, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ConstructionWorkAreaJPanel cwajp = (ConstructionWorkAreaJPanel) component;
        cwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        if(Validation.validateTextFieldsForNonEmpty(resultJTextField)){
        request.setResult(resultJTextField.getText());
        request.setStatus("Completed"); 
        if(request.getCategory().equalsIgnoreCase("public")){
            try {
                Helper.updateCitizenQueue(buisness, request.getGroupId());
            } catch (IOException ex) {
                Logger.getLogger(ElectricityProcessWorkRequestJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        JOptionPane.showMessageDialog(null, "Message Sent successfully!", "Success", JOptionPane.WARNING_MESSAGE);
        resultJTextField.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Message!");
        }
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void resultJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultJTextFieldKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_resultJTextFieldKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
