/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CitizenRole;

import Business.Address.Address;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.CitizenEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Municipal.CitizenOrganization;
import Business.Organization.Organization;
import Business.Person.CitizenOrganizationEmployee;
import Business.Role.CitizenRole;
import Business.Utility.OTPSender;
import Business.Utility.Validation;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prashant
 */
public class CitizenRegistration extends javax.swing.JPanel {
       
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    /**
     * Creates new form CitizenRegistration
     */ 
      private  JPanel userProcessContainer;
      private  Organization org;
      private  EcoSystem system;
      private  String OTP_GEN="";
        
    public CitizenRegistration(JPanel userProcessContainer, Organization org, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
                this.org = org;
                this.system = system;
                populateNetworkComboBox();
    }

    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            networkJComboBox.addItem(network);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        passwordJTxt = new javax.swing.JTextField();
        firstNameJTxt1 = new javax.swing.JTextField();
        maleJRadiobtn = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        pincodeJTxt = new javax.swing.JTextField();
        lastNameJTxt1 = new javax.swing.JTextField();
        ageJTxt1 = new javax.swing.JTextField();
        userNameJTxt = new javax.swing.JTextField();
        sumbitJBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        phoneNoJTxt2 = new javax.swing.JTextField();
        emailIdJTxt1 = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        OTPBtn = new javax.swing.JButton();
        OTPTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addtxt1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        addTxt2 = new javax.swing.JTextField();
        aptNumberTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 0));
        setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Email Id");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("First Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Last Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Gender");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 70, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Age");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 40, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Address Line 1");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Pincode");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 70, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Phone Number");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 120, 30));

        passwordJTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordJTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(passwordJTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 210, 30));

        firstNameJTxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameJTxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        firstNameJTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameJTxt1KeyTyped(evt);
            }
        });
        jPanel2.add(firstNameJTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 210, 30));

        maleJRadiobtn.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(maleJRadiobtn);
        maleJRadiobtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maleJRadiobtn.setText("Male");
        maleJRadiobtn.setAutoscrolls(true);
        maleJRadiobtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        maleJRadiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleJRadiobtnActionPerformed(evt);
            }
        });
        jPanel2.add(maleJRadiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 80, -1));

        jRadioButton2.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.setAutoscrolls(true);
        jRadioButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 90, -1));

        pincodeJTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pincodeJTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pincodeJTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pincodeJTxtKeyTyped(evt);
            }
        });
        jPanel2.add(pincodeJTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 210, 30));

        lastNameJTxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameJTxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lastNameJTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameJTxt1KeyTyped(evt);
            }
        });
        jPanel2.add(lastNameJTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 210, 30));

        ageJTxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ageJTxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ageJTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageJTxt1KeyTyped(evt);
            }
        });
        jPanel2.add(ageJTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 210, 30));

        userNameJTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userNameJTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(userNameJTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 210, 30));

        sumbitJBtn.setBackground(new java.awt.Color(51, 51, 51));
        sumbitJBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sumbitJBtn.setForeground(new java.awt.Color(255, 255, 255));
        sumbitJBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Pictures/1417678138_list-add-user.png"))); // NOI18N
        sumbitJBtn.setText("Register");
        sumbitJBtn.setFocusTraversalPolicyProvider(true);
        sumbitJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbitJBtnActionPerformed(evt);
            }
        });
        jPanel2.add(sumbitJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 210, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Password");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 80, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("User Name");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 90, 30));

        phoneNoJTxt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneNoJTxt2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        phoneNoJTxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNoJTxt2KeyTyped(evt);
            }
        });
        jPanel2.add(phoneNoJTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 210, 30));

        emailIdJTxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailIdJTxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(emailIdJTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 210, 30));

        backJButton.setBackground(new java.awt.Color(51, 51, 51));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Pictures/1417743630_go-previous-24.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 1, 28)); // NOI18N
        jLabel13.setText("New Citizen Register Here");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 340, 40));

        jLabel14.setOpaque(true);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 90));

        OTPBtn.setBackground(new java.awt.Color(51, 51, 51));
        OTPBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OTPBtn.setForeground(new java.awt.Color(255, 255, 255));
        OTPBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Pictures/if_Bubble_chat_check_comment_conversation_done_message_1886490.png"))); // NOI18N
        OTPBtn.setText("Send OTP");
        OTPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTPBtnActionPerformed(evt);
            }
        });
        jPanel2.add(OTPBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 150, 40));

        OTPTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OTPTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        OTPTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OTPTxtKeyTyped(evt);
            }
        });
        jPanel2.add(OTPTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 210, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("OTP");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 50, 30));

        addtxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addtxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(addtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 210, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Address Line 2");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 120, 30));

        addTxt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addTxt2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(addTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 210, 30));

        aptNumberTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aptNumberTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        aptNumberTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aptNumberTxtKeyTyped(evt);
            }
        });
        jPanel2.add(aptNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 210, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Apt Number");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 100, 30));

        networkJComboBox.setBackground(new java.awt.Color(153, 153, 153));
        networkJComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        networkJComboBox.setForeground(new java.awt.Color(255, 255, 255));
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 210, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("City");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, 30));

        add(jPanel2, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void pincodeJTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pincodeJTxtKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_pincodeJTxtKeyTyped

    private void ageJTxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageJTxt1KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_ageJTxt1KeyTyped

    private void sumbitJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbitJBtnActionPerformed
       // TODO add your handling code here:

        try {
            String firstName = firstNameJTxt1.getText();
            String lastName = lastNameJTxt1.getText();
            int age = Integer.parseInt(ageJTxt1.getText());
            String userName = userNameJTxt.getText();
            String password = passwordJTxt.getText();
            String addressLine1 = addtxt1.getText();
            String addressLine2 = addTxt2.getText();
            int aptNumber=Integer.parseInt(aptNumberTxt.getText());
            int pincode = Integer.parseInt(pincodeJTxt.getText());
            String phoneNo=phoneNoJTxt2.getText();
            String otp_txt=OTPTxt.getText();
           // int phoneNo = Integer.parseInt(str);
            String email = emailIdJTxt1.getText();

            String gender;

            if (maleJRadiobtn.isSelected()) {
                gender = "Male";
            } else {
                gender = "Female";
            }
            
            if (firstName.length() == 0 | firstName == null | email.length() == 0
                | email == null | lastName.length() == 0 | lastName == null
                | gender.length() == 0 | addressLine1 == null | addressLine1.length() == 0
                | userName.length() == 0 | userName == null | password.length() == 0
                | password == null | otp_txt==null) {
                JOptionPane.showMessageDialog(null, "Please Complete all required fields");
            }
            else if(!Validation.validateTextFieldsForInteger(ageJTxt1)){
                JOptionPane.showMessageDialog(null,"Please enter Valid Age");
            }
            else if(pincodeJTxt.getText().length() != 5){
                JOptionPane.showMessageDialog(null,"Please enter valid Pin Code");
            }
            else  if(!Validation.validateTextFieldsForEmailId(emailIdJTxt1))
            {
                JOptionPane.showMessageDialog(null,"Please enter valid email id");
            }
            else if(!Validation.validateTextFieldsForPhoneNumber(phoneNoJTxt2))
            {
                JOptionPane.showMessageDialog(null,"Please enter valid Primary Phone Number");

            }
            else if(OTPTxt.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"Please enter OTP");

            }

            else {
                boolean isContain = Validation.checkUniquenessOfUserName(userName, system);
                boolean isPhone= Validation.checkUniquenessOfPhoneNumber(phoneNo, system);
                if (isContain) {
                    JOptionPane.showMessageDialog(null, "UserAccount Already exists", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                else if(isPhone){
                    JOptionPane.showMessageDialog(null, "Phone Number Already exists", "Warning", JOptionPane.WARNING_MESSAGE);
                } 
                else if(!otp_txt.equals(OTP_GEN)) {
                         
                        JOptionPane.showMessageDialog(null, "Incorrect OTP Please Enter again and Click on Submit", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                else {
                    Address address=new Address();
                    address.setAddressLine1(addressLine1);
                    address.setAddressLine2(addressLine2);
                    address.setApartmentNo(aptNumber);
                    address.setZipCode(pincode);
                    address.setCity(networkJComboBox.getSelectedItem().toString());
                    Network network=(Network) networkJComboBox.getSelectedItem();
                    for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                        if(enterprise instanceof CitizenEnterprise){
                        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                            if(organization instanceof CitizenOrganization){
                                CitizenOrganizationEmployee coe = (CitizenOrganizationEmployee) organization.getPersonDirectory().createDirectAidEmp(firstName, lastName, email, gender, age, address, phoneNo, pincode, org);
                                organization.getUserAccountDirectory().createUserAccount(userName, password,coe, new CitizenRole());
                            }
                        }
                    }
                    }
                    
                    userProcessContainer.removeAll();
                    JOptionPane.showMessageDialog(null, "Successfully registered");
                    firstNameJTxt1.setText("");
        lastNameJTxt1.setText("");
        ageJTxt1.setText("");
        userNameJTxt.setText("");
        passwordJTxt.setText("");
        addtxt1.setText("");
        addTxt2.setText("");
        aptNumberTxt.setText("");
        pincodeJTxt.setText("");
        phoneNoJTxt2.setText("");
        OTPTxt.setText("");
        emailIdJTxt1.setText("");
                }

            }
        } catch (NumberFormatException num) {
            JOptionPane.showMessageDialog(null, "Please provide All Details", "Incorrect Input", JOptionPane.WARNING_MESSAGE);
        } catch (NullPointerException nul) {
            JOptionPane.showMessageDialog(null, "Please Select Gender", "Incomplete Input", JOptionPane.WARNING_MESSAGE);

        }
        
    }//GEN-LAST:event_sumbitJBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
//        logoutJButton.setEnabled(false);
//        userNameJTextField.setEnabled(true);
//        passwordField.setEnabled(true);
//        loginJButton.setEnabled(true);
//
//        userNameJTextField.setText("");
//        passwordField.setText("");

        userProcessContainer.removeAll();
        JPanel blankJP = new JPanel();
        userProcessContainer.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void OTPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTPBtnActionPerformed
        try {
            // TODO add your handling code here:
            boolean flag=true;
            String phoneNo=phoneNoJTxt2.getText();
          if(!Validation.validateTextFieldsForPhoneNumber(phoneNoJTxt2))
            {
                JOptionPane.showMessageDialog(null,"Please enter valid Primary Phone Number");
                flag=false;

            }
           boolean isPhone= Validation.checkUniquenessOfPhoneNumber(phoneNo, system);
                if (isPhone) {
                    JOptionPane.showMessageDialog(null, "Phone Number Already exists", "Warning", JOptionPane.WARNING_MESSAGE);
                    flag=false;
                }
           if(flag){
            
            OTP_GEN=OTPSender.OTP(4);
            OTPSender.send(OTP_GEN, "+1"+phoneNo);
            System.err.println(OTP_GEN);
             }
        } catch (IOException ex) {
            Logger.getLogger(CitizenRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OTPBtnActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void maleJRadiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleJRadiobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleJRadiobtnActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void phoneNoJTxt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoJTxt2KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_phoneNoJTxt2KeyTyped

    private void aptNumberTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aptNumberTxtKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_aptNumberTxtKeyTyped

    private void OTPTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OTPTxtKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_OTPTxtKeyTyped

    private void firstNameJTxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameJTxt1KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isLetter(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE || character == KeyEvent.VK_SPACE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_firstNameJTxt1KeyTyped

    private void lastNameJTxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameJTxt1KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isLetter(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE || character == KeyEvent.VK_SPACE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_lastNameJTxt1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OTPBtn;
    private javax.swing.JTextField OTPTxt;
    private javax.swing.JTextField addTxt2;
    private javax.swing.JTextField addtxt1;
    private javax.swing.JTextField ageJTxt1;
    private javax.swing.JTextField aptNumberTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailIdJTxt1;
    private javax.swing.JTextField firstNameJTxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField lastNameJTxt1;
    private javax.swing.JRadioButton maleJRadiobtn;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JTextField passwordJTxt;
    private javax.swing.JTextField phoneNoJTxt2;
    private javax.swing.JTextField pincodeJTxt;
    private javax.swing.JButton sumbitJBtn;
    private javax.swing.JTextField userNameJTxt;
    // End of variables declaration//GEN-END:variables
}
