/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CitizenRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Municipal.CitizenOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkeQueue.ConstructionWorkRequest;
import Business.WorkeQueue.ElectricityWorkRequest;
import Business.WorkeQueue.TransportWorkRequest;
import Business.WorkeQueue.WaterSupplyWorkRequest;
import Business.WorkeQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class CitizenWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private CitizenOrganization citizenOrganization;
    private UserAccount userAccount;
    private EcoSystem business;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CitizenWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CitizenOrganization citizenOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.citizenOrganization = citizenOrganization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business =  business;
        valueLabel.setText(enterprise.getName());
//        userAccount.getWorkQueue().getWorkRequestList().clear();
        populateRequestTable();
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            String result = null;
            System.out.println(request.getRequestType());
            if(request.getRequestType().equals(WorkRequest.WorkRequestType.ElectricityWorkRequest.getValue())){
               result = ((ElectricityWorkRequest) request).getResult();
            }else if(request.getRequestType().equals(WorkRequest.WorkRequestType.ConstructionWorkRequest.getValue())){
               result = ((ConstructionWorkRequest) request).getResult();
            }else if(request.getRequestType().equals(WorkRequest.WorkRequestType.WaterSupplyWorkRequest.getValue())){
               result = ((WaterSupplyWorkRequest) request).getResult();
            }
            row[3] = result == null ? "Waiting" : result;
            row[4]= request.getGroupId() == null ? "N/A" : request.getGroupId();
            model.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestTestJButton = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        escalateRequestBtn = new javax.swing.JButton();
        btnSendFeedback = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setBackground(new java.awt.Color(51, 51, 51));
        workRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        workRequestJTable.setForeground(new java.awt.Color(255, 255, 255));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Area Name", "Receiver", "Status", "Result", "GroupId"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(20);
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 650, 190));

        requestTestJButton.setBackground(new java.awt.Color(51, 51, 51));
        requestTestJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestTestJButton.setForeground(new java.awt.Color(255, 255, 255));
        requestTestJButton.setText("Request Problem");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, 40));

        refreshTestJButton.setBackground(new java.awt.Color(51, 51, 51));
        refreshTestJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refreshTestJButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 100, 40));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 110, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 110, 26));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Citizen Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, -1));

        escalateRequestBtn.setBackground(new java.awt.Color(51, 51, 51));
        escalateRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        escalateRequestBtn.setForeground(new java.awt.Color(255, 255, 255));
        escalateRequestBtn.setText("Escalate Request");
        escalateRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalateRequestBtnActionPerformed(evt);
            }
        });
        add(escalateRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, 40));

        btnSendFeedback.setBackground(new java.awt.Color(51, 51, 51));
        btnSendFeedback.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSendFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnSendFeedback.setText("Send Feedback");
        btnSendFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFeedbackActionPerformed(evt);
            }
        });
        add(btnSendFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestLabTestJPanel", new ProcessCitizienRequestJPanel(userProcessContainer, userAccount, enterprise, business));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();
        
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void escalateRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalateRequestBtnActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        if(request.getResolveDate()==null){
            int diffInDays = (int) ((new Date().getTime() - request.getRequestDate().getTime()) / (1000 * 60 * 60 * 24));
            System.out.println(diffInDays+" Diff in days");
            if(diffInDays > 15){
                request.setStatus("Escalated");
            }else JOptionPane.showMessageDialog(null, "Request can not be escalated before 15 days of request date");
        }else JOptionPane.showMessageDialog(null, "Request already resolved");
        
        populateRequestTable();
    }//GEN-LAST:event_escalateRequestBtnActionPerformed

    private void btnSendFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFeedbackActionPerformed
        // TODO add your handling code here:
        SendFeedbackJPanel sendFeedbackJPanel = new SendFeedbackJPanel(userProcessContainer, userAccount, citizenOrganization,enterprise);
        userProcessContainer.add("SendFeedbackJPanel", sendFeedbackJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSendFeedbackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendFeedback;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton escalateRequestBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
