/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CitizenRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Municipal.CitizenOrganization;
import Business.UserAccount.UserAccount;
import Business.Utility.Validation;
import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.JPanel;
import javax.mail.*;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
/**
 *
 * @author harsh
 */
public class SendFeedbackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SendFeedbackJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private CitizenOrganization citizenOrganization;
    private UserAccount userAccount;
    private EcoSystem business;
    
    private static String USER_NAME = "harshgirme22";  // GMail user name (just the part before "@gmail.com")
        private static String PASSWORD = "mcrack2017"; // GMail password
        private static String RECIPIENT = "harshgirme@gmail.com";
    
    public SendFeedbackJPanel(JPanel userProcessContainer,UserAccount account, CitizenOrganization citizenOrganization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.citizenOrganization = citizenOrganization;
        this.enterprise = enterprise;
        this.userAccount = account;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnSendMail = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton2.setBackground(new java.awt.Color(51, 51, 51));
        backJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Pictures/1417743630_go-previous-24.png"))); // NOI18N
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });
        add(backJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Send Feedback");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 888, -1));

        txtMessage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 98, 464, 274));

        btnSendMail.setBackground(new java.awt.Color(51, 51, 51));
        btnSendMail.setForeground(new java.awt.Color(255, 255, 255));
        btnSendMail.setText("Send Mail");
        btnSendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMailActionPerformed(evt);
            }
        });
        add(btnSendMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed

    
    private void btnSendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMailActionPerformed
        
        
    
        String from = USER_NAME;
        String pass = PASSWORD;
        String[] to = { RECIPIENT }; // list of recipient email addresses
        String subject = "Feedback from User";
        String body= "";
        if(Validation.validateTextFieldsForNonEmpty(txtMessage)){
            body = txtMessage.getText();
            sendFromGMail(from, pass, to, subject, body);
     
            JOptionPane.showMessageDialog(null, "Mail Sent Successfully!!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Give Input for Feedback", "Incomplete Input", JOptionPane.WARNING_MESSAGE);
        }

        
    }//GEN-LAST:event_btnSendMailActionPerformed

    private static void sendFromGMail(String from, String pass, String[] to, String subject, String body) {
        Properties props = System.getProperties();
        String host = "smtp.gmail.com";
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.user", from);
        props.put("mail.smtp.password", pass);
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");

        Session session = Session.getDefaultInstance(props);
        MimeMessage message = new MimeMessage(session);

        try {
            message.setFrom(new InternetAddress(from));
            InternetAddress[] toAddress = new InternetAddress[to.length];

            // To get the array of addresses
            for( int i = 0; i < to.length; i++ ) {
                toAddress[i] = new InternetAddress(to[i]);
            }

            for( int i = 0; i < toAddress.length; i++) {
                message.addRecipient(Message.RecipientType.TO, toAddress[i]);
            }

            message.setSubject(subject);
            message.setText(body);
            Transport transport = session.getTransport("smtp");
            transport.connect(host, from, pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
        }
        catch (AddressException ae) {
            ae.printStackTrace();
        }
        catch (MessagingException me) {
            me.printStackTrace();
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton2;
    private javax.swing.JButton btnSendMail;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
